# Generated by Django 3.2 on 2023-06-05 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_tag_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipetag',
            old_name='tag',
            new_name='tags',
        ),
    ]
