# Generated by Django 3.2 on 2023-06-06 15:35

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_rename_tag_recipetag_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipetag',
            old_name='tags',
            new_name='tag',
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(choices=[('#F5B151', 'breakfast'), ('#BBE2BB', 'lunch'), ('#B1A7E2', 'dinner')], default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
    ]
