# Generated by Django 3.2 on 2023-06-06 15:50

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20230606_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=[('#F5B151', 'breakfast'), ('#BBE2BB', 'lunch'), ('#B1A7E2', 'dinner')]),
        ),
    ]
